# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://repartee-per-se.com/"  # Include trailing slash
title = "Repartee, per se"
author = "AR Domingo"
copyright = "Copyright Â© 2021, Andres Domingo; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "hugo-clarity"

disqusShortname = ""

#DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

# Enable analytics by entering your Google Analytics tracking ID
<<<<<<< HEAD
GoogleAnalytics = "G-9LMWHZE4LB"
=======
GoogleAnalytics = "G-9LMWHZE4LB""
>>>>>>> d9eb3b9dbe824f0fcd4faf6bfaeb296423cdf622


[taxonomies]
category = "categories"
tag = "tags"
series = "series"
